# Generated by Django 5.1.4 on 2024-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
