# Generated by Django 5.1.4 on 2024-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('salary', '工资'), ('shopping', '购物'), ('dining', '餐饮'), ('rent', '房租'), ('commute', '通勤')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10),
        ),
    ]
